[project]
name = "ascend-simulator-benchmark-platform"
version = "0.1.0"
description = "Backend for Ascend Simulator and Benchmark Platform"
requires-python = ">=3.10"
dependencies = [
    "fastapi[standard]",
    "pydantic-settings",
    "SQLAlchemy",
    "psycopg[binary]",
    "alembic",
    "pyYAML",
    "python-multipart",
]

[tool.fastapi]
entrypoint = "app.main:app"
