[project]
name = "ascend-simulator-benchmark-platform"
version = "0.1.0"
description = "Backend for Ascend Simulator and Benchmark Platform"
requires-python = ">=3.10"
dependencies = [
    "chip-performance-analysis",
    "fastapi[standard]",
    "pydantic-settings",
    "SQLAlchemy",
    "psycopg[binary]",
    "alembic",
    "pyYAML",
    "python-multipart",
    "httpx",
]

[tool.uv.sources]
chip-performance-analysis = { path = "../analysis_tools", editable = true }

[tool.fastapi]
entrypoint = "app.main:app"
